spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

springdoc:
  packages-to-scan: software.sigma.internship.controller
  paths-to-match: /**

cors:
  allow-origin: http://localhost:4200

runAfterTests:
  retrievingStatData: true