name: Build
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  code-coverage:
    runs-on: ubuntu-latest
    name: Code Coverage
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven
      - name: Run Tests
        run: |
          mvn clean verify
      - name: Upload Code Coverage Report
        uses: codecov/codecov-action@v3
